### ISSUE TITLE
/turnstile command missing in help

### ISSUE THREAD

**Issue by Bloodlex** [Lxmune/turnstile-rewrite#12]
Hello 🙂 

As in the title 🙂 .

Best regards,
Bloodlex

**Comment by Lxmune** [comment]
My bad, I didn't have the time to check all the changes I've made.

Going to fix that in the next 24h

**Comment by Bloodlex** [comment]
> My bad, I didn't have the time to check all the changes I've made.
> 
> Going to fix that in the next 24h

Sure, don't worry, take your time 🙂 . Thank you.

**Comment by Lxmune** [comment]
Resolved in the next update.
