### ISSUE TITLE
Fence post forgets it's position after restart (not connecting to walls)

### ISSUE THREAD

**Issue by Bloodlex** [Lxmune/turnstile-rewrite#18]
I've just noticed that after a server restart, a fence post "forgets" about it's position and is no longer connected to neighbouring walls

**Comment by Lxmune** [comment]
I will force the fences to re-spawn at every reboot.

Fixed the next update, thanks for the feedback again 👍

**Comment by Bloodlex** [comment]
> I will force the fences to re-spawn at every reboot.
> 
> Fixed the next update, thanks for the feedback again 👍

Great, it's working, thank you 🙂.
