### ISSUE TITLE
Respect item's properties (name, lore, NBT tags) with /turnstile item

### ISSUE THREAD

**Issue by Bloodlex** [Lxmune/turnstile-rewrite#24]
Hey,

I have a lot of custom items on my server. I think it would be nice if a Turnstile accepted only items, that share the same properties - NBT tags, name, description and so on.

Thanks to that we could make some custom items (tickets) and for instance sell them. These could be represented by, let's say, sunflower item, but of course we wouldn't like vanilla item to work the same way as changed item.

**Example with some POTION with custom name, lore and NBT**
![image](https://user-images.githubusercontent.com/1086720/209975568-15e40fc4-bd23-46b5-a190-861774ccfa6d.png)

**Bed with custom name**
![image](https://user-images.githubusercontent.com/1086720/209976115-bd5af57a-0fdd-4c89-808a-5c0670fda86b.png)

**Comment by Lxmune** [comment]
That's a clever idea, I will make some research regarding this change.

Thanks for including an item example, it will make my work easier 😎

**Comment by Bloodlex** [comment]
> That's a clever idea, I will make some research regarding this change.
> 
> Thanks for including an item example, it will make my work easier 😎

Sure, let me know if you need anything 🙂 .

**Comment by Lxmune** [comment]
As for the moment, I added the support for custom name & lore. As for the other parameters, we could see it coming in another update. 👍

**Comment by Bloodlex** [comment]
> As for the moment, I added the support for custom name & lore. As for the other parameters, we could see it coming in another update. 👍

Great, thanks! 🙂
