### ISSUE TITLE
Fetch economy currency sign from Vault/other provider in messages

### ISSUE THREAD

**Issue by Bloodlex** [Lxmune/turnstile-rewrite#25]
Hey, would be nice to have it in order not to hard-code it in messages 🙂.

![image](https://user-images.githubusercontent.com/1086720/209979310-bbf35876-0f39-4254-b3d8-1d1fa5ea7b00.png)

**Comment by Lxmune** [comment]
Added in the next update 👍

**Comment by Lxmune** [comment]
As for the other/custom provider, I won't be able to get the variables, since I would need to import other packages.

I made it non-hardcoded, so you can change the {CURRENCY} value to your wishing.

**Comment by Bloodlex** [comment]
> As for the other/custom provider, I won't be able to get the variables, since I would need to import other packages.
> 
> I made it non-hardcoded, so you can change the {CURRENCY} value to your wishing.

Great, thank you! 🙂
