### ISSUE TITLE
From huuliveikko: Add gate support

### ISSUE THREAD

**Issue by Lxmune** [Lxmune/turnstile-rewrite#9]
> hi Can you put your Fence Gate on the list also?

**Comment by Bloodlex** [comment]
> > hi Can you put your Fence Gate on the list also?

As discussed, not possible, right?

**Comment by Lxmune** [comment]
> > > hi Can you put your Fence Gate on the list also?
> 
> As discussed, not possible, right?

Yep, forgot to close it.

Not possible since players could theorically go past the gates if they spam them enough, since they are thin.

**Comment by Bloodlex** [comment]
Sure, let's forget about that then 🙂.
